version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ansible-layer"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-dkox31cmicuj"
s3_prefix = "ansible-layer"
region = "eu-west-3"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
